set(DMP_BENCHMARKS_MULTITHREAD ${DMP_BENCHMARKS}.Multithread)
##############################################################################
# Multithread benchmarks
##############################################################################
add_subdirectory(resource_pool)
##############################################################################
