name: Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-toolchain-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      toolchain_changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for toolchain changes
        id: check
        run: |
          # Get the previous commit on main
          PREV_COMMIT=$(git rev-parse HEAD^1)
          
          # Compare with current commit
          git diff --name-only $PREV_COMMIT HEAD > changed_files.txt
          
          if grep -q "infrastructure/toolchain/" changed_files.txt || grep -q "vcpkg.json" changed_files.txt; then
            echo "Toolchain files changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No toolchain files changed"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  publish-toolchain:
    needs: check-toolchain-changes
    if: needs.check-toolchain-changes.outputs.toolchain_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        id: env
        uses: ./.github/actions/env-setup
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker system prune -af
          df -h

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: infrastructure/toolchain/Dockerfile
          target: toolchain
          push: true
          tags: |
            ghcr.io/${{ steps.env.outputs.owner }}/dmp_toolchain:stable
            ghcr.io/${{ steps.env.outputs.owner }}/dmp_toolchain:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ steps.env.outputs.owner }}/dmp_toolchain:cache
          cache-to: type=registry,ref=ghcr.io/${{ steps.env.outputs.owner }}/dmp_toolchain:cache,mode=max